# Generated by Django 4.0.6 on 2022-08-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10),
        ),
    ]
