# Generated by Django 4.0.6 on 2022-08-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='City',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(auto_created=True, default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='FullName',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PinCode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='State',
            field=models.CharField(default='', max_length=35),
        ),
    ]
